language: node_js

node_js:
  - "8"
  - "10"

script:
  - npm run test
  - npm run build
  - npm run size

notifications:
  email:
    on_failure: change

after_success: "npm run coveralls"

cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
