language: node_js

env:
  global:
    - YARN_VERSION="1.21.1"
    - NODE_VERSION="12.16.0"

node_js:
  - $NODE_VERSION

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

# if before_script returns a non-zero exit code, the build is errored and stops
# immediately.
before_script:
  - yarn build
  - yarn lint-js --max-warnings=0
  - yarn lint-ts

# If script returns a non-zero exit code, the build is failed, but continues to
# run before being marked as failed.
script:
  - yarn test
  - yarn size

notifications:
  email:
    on_failure: change

after_success: "npm run coveralls"

cache:
  yarn: true
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
