language: node_js

env:
  global:
    - YARN_VERSION="1.21.1"

node_js:
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn test
  - yarn build
  - yarn size

notifications:
  email:
    on_failure: change

after_success: "npm run coveralls"

cache:
  yarn: true
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
